### ISSUE TITLE
Maven update 

### ISSUE THREAD

**Issue by karopyszcz** [salesforce-marketingcloud/FuelSDK-Java#77]
Hi, 
please revide the version uplouded to maven, because it seems to be something much older than the 1.2.1. 1.2.2 isn't even available.
Thank you

**Comment by sharif26** [comment]
Thanks for notifying us the issue.
For some reason, the repo is not correctly pushed from oss sonatype (https://oss.sonatype.org/) to maven repo(http://repo.maven.apache.org/maven2/) when we released.
And we checked on oss sonatype repo, but did not check on the maven repo from where the dependencies are actually downloaded.
The issue is fixed, thanks for your patience, please let us know if we face any difficulty using the new version.
